apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
  labels:
    app: frontend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
spec:
  type: ClusterIP
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
