apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prashantbat/devops-ai-playbook.git'
    targetRevision: main
    path: gitops
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boutique
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
